### PR TITLE
Add ALPN Jars Directly To Image

### PR DESCRIPTION
**Pull request by waprin**
This is to workaround some connectivity issues to maven.

### CODE REVIEW

**Comment by lesv** [comment]
Why are we doing this?

**Comment by lesv** [comment]
No - let's not do this.

**Comment by waprin** [comment]
We are doing this so the Docker builds reliably work. Otherwise they don't. This is per recommendation of @ludoch .

**Comment by lesv** [comment]
Please use the URL's I sent you instead of checking these into this repo.

**Pull request closed without merging**
