### PR TITLE
Further simplify java Hello World

### PR DESCRIPTION
**Pull request by garye**
- Go back to using plugin to detect os
- Remove unnecessary maven config for packaging
- Use system properties for project/zone/cluster for consistency
  with other examples.
- Only require java 1.7 - works on cloud shell with java 1.7 installed

### CODE REVIEW

**Comment by ludoch** [comment]
Cloud shell can use Java 8. I would use Java 8 in the sample.

**Comment by lesv** [comment]
It should be Java 8 for all samples.
Cloud shell users should `sudo update-java-alternatives -s java-1.8.0-openjdk-amd64`

**Comment by lesv** [comment]
Once you change to java 1.8, add the cloud shell comment to the readme -- LGTM -- Thank you

**Comment by sduskis** [comment]
Can we use 1.7 for now and then switch to 1.8 in our pom.xml when cloud shell defaults to Java 1.8?  Fewer steps are better, IMHO.

**Comment by sduskis** [comment]
We were at a client site today, and this was an issue.  We want the lowest possible barrier of entry for our examples.  They should just work.

**Comment by lesv** [comment]
Understood, but we are trying to move everything to J8.  LGTM for now.

**Pull request merged**
