### PR TITLE
Remove zone default in BigtableHelper.java

### PR DESCRIPTION
**Pull request by carterpage**

### CODE REVIEW

**Comment by lesv** [comment]
I'm sure there is a reason you want this, so LGTM.

**Comment by lesv** [comment]
Carter - can you sign the CLA, by going to github/ internally.

**Comment by carterpage** [comment]
I signed it!

**Comment by carterpage** [comment]
Actually I didn't sign it. But please take a look. I've contributed plenty of code to GCP, and my username is a registered Google Cloud Platform member.

The link says, "Googlers do not need to sign a CLA. "

**Pull request merged**
