### PR TITLE
Use Dataflow flex templates

### PR DESCRIPTION
**Pull request by anantdamle**
* Fix typo in CsvImport class
* Add support to create Dataflow flex template

### CODE REVIEW

**Comment by anantdamle** [comment]
@billyjacobson can you please review the changes and merge.

**Comment by billyjacobson** [comment]
This seems like this is adding a lot more complexity to this example for anyone who wants to just get it up and running? Also, this code is not tested at all and this repository is being deprecated since there any many code examples that have fallen out of use. If this example is important to keep modifying and updating, it would be better suited to live in the [java-docs-samples ](https://github.com/GoogleCloudPlatform/java-docs-samples/tree/main/bigtable/beam) repo or in [java-bigtable](https://github.com/googleapis/java-bigtable) and get released as a supported tool

**Comment by anantdamle** [comment]
@billyjacobson thanks for the input. When is the deprecation date. two of my customers are using/planning to use this in production

**Comment by billyjacobson** [comment]
> @billyjacobson thanks for the input. When is the deprecation date. two of my customers are using/planning to use this in production

This repo is currently not in use. If you need to use this example, I would recommend making a fork of the code and putting it somewhere your team can use it as this specific example goes along with a blog post, so these changes are going to make it inconsistent with how to use the blog post. 

Once it's in your own repo or your team's repo you can do whatever you want with it. This code is just meant to be used as a starting point not a production tool

**Pull request closed without merging**
