### PR TITLE
Upgrading java examples to 1.0.0-pre3

### PR DESCRIPTION
**Pull request by sduskis**
- I upgraded all java projects to 1.0.0-pre3 to the 1.x artifacts.
- The change from 1.3 to 1.x required a couple of changes to the imports, since the classes were using classes that are shaded in 1.3, but not in 1.x
- Coinbase was using the Cloud Bigtable API v1 cluster/zone instead of instance, so I updated the class to use instance.  It also had a copy of `CloudBigtableOptions`, so I used the class that comes with the CloudBigtableIO package.
- The dataproc-wordcount used a directory called com.example.bigtable.sample, which doesn't compy with the standard maven approach. I moved the classes to /com/example/bigtable/sample/ instead.

### CODE REVIEW

**Comment by lesv** [comment]
@waprin FYI

**Comment by sduskis** [comment]
We now actually have a dependency in cloud-bigtable-core on the latest tcnative BoringSSL.  The newest BoringSSL can be shaded and renamed, which allows our shaded HBase clients to coexist with older versions of BoringSSL.  I'll remove all of the dependency in another PR.

**Review by Radikillu6 — COMMENTED** [review]
[]java/dataflow-coinbase/dataflow/src/main/java/com/google/cloud/examples/coinflow/sources/CoinbaseSource.java(url)

**Review by Radikillu6 — COMMENTED** [review]
]java/dataflow-coinbase/dataflow/src/main/java/com/google/cloud/examples/coinflow/sources/CoinbaseSource.java(url)[debug]

**Comment by kolea2** [comment]
@JustinBeckwith

**Review by kolea2 — COMMENTED** [review]
@JustinBeckwith

**Pull request merged**
