### PR TITLE
Jetty annotations

### PR DESCRIPTION
**Pull request by lesv**
Remove 0.2.1 bug …
0.2.1 required that you include as a dependency HBase-client - this is no longer required.
Upgrade to 0.2.3 client

### CODE REVIEW

**Comment by lesv** [comment]
@sduskis This should be merged after 0.2.3 is released.  (I'm sending it to you, just in case that happens after Thursday.)

**Comment by kevinsi4508** [comment]
you mean after 0.2.2 is released, correct?

**Comment by lesv** [comment]
What ever you call it.  The last thing I was asked to check against was 0.2.3-SNAPSHOT.  It seems like things have morphed a bit.  (I hard coded 0.2.3, but that's trivial to change back to 0.2..2)

**Comment by lesv** [comment]
@sduskis @kevinsi4508 Please merge when the client shows up on maven central.
@IanLewis FYI - I simplified your simple-cli a bit, you might be interested in how.
@hegemonic FYI

**Pull request merged**
