### PR TITLE
Link to python-docs-samples in README.

### PR DESCRIPTION
**Pull request by tswast**
Fixes https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/issues/197.

### CODE REVIEW

**Comment by lesv** [comment]
LGTM - in time we'll move Java, but not yet.

**Comment by lesv** [comment]
Though shouldn't the main README also change?

**Comment by tswast** [comment]
Oh, yep. I missed those.

**Comment by tswast** [comment]
Okay, updated the root README as well.

**Comment by lesv** [comment]
LGTM - thanks.

**Pull request merged**
