### PR TITLE
Example for using the dataflow-based HBase sequence file importer for…

### PR DESCRIPTION
**Pull request by weiminyu**
Example of using bigtable-dataflow-import.

### CODE REVIEW

**Comment by lesv** [comment]
LGTM -- any chance there is an open source hbase sequence dataset somewhere?

**Comment by lesv** [comment]
Did you mean to require the 0.2.4-SNAPSHOT?

**Comment by weiminyu** [comment]
For now, yes. Import support did not make it in to Client API v0.2.3.

**Comment by sduskis** [comment]
Getting a data set is tricky.  We have to discuss it off line.

**Pull request merged**
