### PR TITLE
chore: remove unused dataproc and simple perf examples

### PR DESCRIPTION
**Pull request by kolea2**

### CODE REVIEW

**Comment by fpaganetto** [comment]
Where can I find these examples officially now? @danieljbruce @kolea2

**Comment by kolea2** [comment]
@fpaganetto you can find some benchmark test scenarios at https://github.com/googleapis/java-bigtable-hbase/tree/main/bigtable-hbase-1.x-parent/bigtable-hbase-1.x-benchmarks

You can also find Bigtable HBase samples at https://github.com/GoogleCloudPlatform/java-docs-samples

**Comment by fpaganetto** [comment]
Okay I was just asking since the second link that appears when trying to find examples of the GCloud `cbt` command is [this file](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/cfa68848531f3f028f7e34b6d94b6ca132a31b32/java/pig/README.md), which has very good examples, and now the link is broken.

image

**Comment by telpirion** [comment]
Hi @fpaganetto ! I'm curious about your usage of the `cbt` commands contained in that file:

- Have you used the [cbt reference documentation](https://cloud.google.com/bigtable/docs/cbt-reference#create_a_column_family)? If so, what can we do to improve it?
- Were you aware that the `cbt` now [has its own repo](https://github.com/googleapis/cloud-bigtable-cbt-cli)? Would you expect to see usage documentation there like what's deleted here?

Thank you!

**Comment by fpaganetto** [comment]
cbt reference documentation is also very clear, that should be also enough

> Would you expect to see usage documentation there like what's deleted here?

It's okay with the [cbt reference documentation](https://cloud.google.com/bigtable/docs/cbt-reference#create_a_column_family).

thanks for answering!

**Pull request merged**
