### PR TITLE
Use shaded jar

### PR DESCRIPTION
**Pull request by lesv**
1. Change to use shaded jar
2. Fix ReadMe in many areas.

### CODE REVIEW

**Comment by lesv** [comment]
@sduskis PTAL

**Comment by sduskis** [comment]
I don't know if we need all of the excludes, but if it works, then LGTM.  We can reduce exclusions later.

**Comment by lesv** [comment]
@sduskis Logging stuff was required.  Xtra Hadoop / HBase not required, but makes things smaller, findbugs/junit - really not required in production.

**Comment by sduskis** [comment]
I'll see if I can exclude some of those dangling dependencies so you don't have to.

**Pull request merged**
