### PR TITLE
Refactor to align with Maven Plugin

### PR DESCRIPTION
**Pull request by waprin**
This commit removes app.yam, and moves the
Docker file and associated image files into
src/main/webapp. This way it aligns
with the maven plugin (supposedly the direction
MVM are moving towards) which makes its easier
to run locally.

### CODE REVIEW

**Comment by lesv** [comment]
Please update gcloud plugin to 2.0.9.76.v20150902 and gae libs to latest.

**Comment by lesv** [comment]
1.9.26 gae plugin

**Comment by lesv** [comment]
LGTM after those changes.

**Comment by lesv** [comment]
Argh! - This really broke the sample - getting rid of the app.yaml was wrong.  -- Sigh.

**Comment by waprin** [comment]
@lesv the sample was already broken as it did not work locally. I was trying to fix it and followed what @ludoch's example said to do.

**Comment by lesv** [comment]
Understood - I was just being grumpy last night.  Change is difficult on folks.

**Comment by waprin** [comment]
:+1: sorry if I made things worse, obviously it's a tricky project!

**Pull request merged**
